config/routes.rb
# Pablo Brusco
#
# This file is part of Alto Taller.
#
# Alto Taller is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Alto Taller is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Alto Taller.  If not, see <http://www.gnu.org/licenses/>.

AltoTaller::Application.routes.draw do
  devise_for :users

  resources :problem_groups do
    resources :problems
  end

  match '/:problem_group_id' => 'students#index', as: 'students'
  match '/:problem_group_id/join' => 'students#join'
  match '/:problem_group_id/submit_info' => 'students#submit_info'
  match '/:problem_group_id/submit_state' => 'students#submit_state'
  match '/:problem_group_id/submit_teacher_state' => 'problems#submit_teacher_state'

  root :to => 'problem_groups#index'
end

app/models/problem_group.rb
# Pablo Brusco
#
# This file is part of Alto Taller.
#
# Alto Taller is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Alto Taller is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Alto Taller.  If not, see <http://www.gnu.org/licenses/>.

class ProblemGroup < ActiveRecord::Base
  attr_accessible :title, :user_id

  validates_presence_of :title

  belongs_to :user
  has_many :problems, dependent: :destroy
  has_many :students, dependent: :destroy

  def join_student(guid)
    students.find_or_create_by_guid(guid)
  end

  def submit_student_info(guid, info)
    return if info.blank?

    student = find_student_by_guid guid
    student.info = info
    student.save!

    send_status_to_student student
  end

  def process_student_state(guid, status)
    student = find_student_by_guid(guid)
    status["problems"].each do |problem|
      solution = solution_for(problem["id"], student.id)
      solution.status = problem["status"]
      solution.code = problem["code"]
      solution.save!
    end

    send_status_to_teacher
  end

  def process_teacher_state(status)
    status["problems"].each do |problem_data|
      problem = Problem.find(problem_data["id"])
      problem.visible = problem_data["visible"]
      problem.save!
    end

    send_status_to_all_students
  end

  def student_status(student)
    student = find_student(student) unless student.is_a?(Student)

    status = student_status_without_guid(student)
    status[:guid] = student.guid
    status
  end

  def teacher_status
    data = []
    problems.each do |problem|
      data << {
        solutions: (problem.visible ? problem_data(problem) : []),
        title: problem.title,
        description: problem.description,
        id: problem.id,
        visible: problem.visible,
      }
    end
    {problems: data}
  end

  def problem_data(problem)
    data = []
    students.each do |student|
      solution = solution_for(problem.id, student.id)
      data << {
        code: solution.code,
        status: solution.status,
        student_id: student.id,
        student_info: student.info,
      }
    end
    data
  end

  def student_status_without_guid(student)
    if student.info.blank?
      return {state: :fill_info}
    end

    {
      state: :solving,
      problems: problems_status_for_student(student),
    }
  end

  def problems_status_for_student(student)
    Problem.visible.where(problem_group_id: student.problem_group_id).map do |problem|
      solution = solution_for(problem.id, student.id)
      {
        title: problem.title,
        description: problem.description,
        status: solution.status,
        code: solution.code,
        id: problem.id,
        default: problem.default,
      }
    end
  end

  def solution_for(problem_id, student_id)
    Solution.find_or_create_by_student_id_and_problem_id(student_id, problem_id)
  end

  def find_student(student_id)
    students.find(student_id)
  end

  def find_student_by_guid(guid)
    students.find_by_guid(guid)
  end

  def send_status_to_all_students
    students.each do |student|
      send_status_to_student student
    end
  end

  def send_status_to_student(student)
    student = find_student(student) unless student.is_a?(Student)

    send_to_student student.guid, student_status(student)
  end

  def send_to_student(guid, data)
    Pusher.send_to_student id, guid, data
  end

  def send_status_to_teacher
    Pusher.send_to_teacher id, teacher_status
  end

  def to_s
    title
  end
end

app/controllers/problem_groups_controller.rb
# Pablo Brusco
#
# This file is part of Alto Taller.
#
# Alto Taller is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Alto Taller is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Alto Taller.  If not, see <http://www.gnu.org/licenses/>.

class ProblemGroupsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @problem_groups = current_user.problem_groups.all
  end

  def new
    @problem_group = current_user.problem_groups.new
  end

  def show
    @problem_group = current_user.problem_groups.find params[:id]
  end

  def create
    @problem_group = current_user.problem_groups.new params[:problem_group]
    if @problem_group.save
      redirect_to problem_groups_path
    else
      render :new
    end
  end

  def destroy
    @problem_group = current_user.problem_groups.find params[:id]
    @problem_group.destroy
    redirect_to problem_groups_path
  end
end

app/views/problem_groups/index.haml
%h3 Mis conjuntos de problemas

%ul.nav
  - @problem_groups.each do |group|
    %li
      %span
        = link_to group, group
        |
        = link_to "borrar", problem_group_path(group), method: :delete, confirm: "Está seguro que quiere borrar el conjunto de problemas '#{group}'?"
  %br
  %li.header= link_to "Crear conjunto de problemas", new_problem_group_path

app/views/problem_groups/new.haml
%h3 Nuevo conjunto de problemas

= form_for @problem_group do |f|
  - if @problem_group.errors.present?
    .alert-container
      .alert.alert-error
        %ul
          - @problem_group.errors.full_messages.each do |msg|
            %li= msg

  %div
    = f.label :title, "Título"
    = f.text_field :title

  %button.btn Guardar

app/views/problem_groups/show.haml
%h3 Problemas de #{@problem_group}
Compartí este link con tus alumnos cuando estés listo para empezar:
- link = students_path(problem_group_id: @problem_group.id, only_path: false)
= link_to link, link

.rows-fluid
  .span8
    .well
      %ul.nav.nav-list
        %li.nav-header
          Problemas
        /ko foreach: problems
        %li
          .link
            %span{ko(click: '$root.deleteProblem')}
              (borrar)
            %span{ko(click: '$root.selectProblem')}
              #{ko_text :title}
            %span.pull-right{data:{bind: "html: showStatus()"}}

        //ko
      %br
      = link_to "Crear nuevo", new_problem_group_problem_path(@problem_group)



    /ko with: selectedProblem
    .well
      %span
        %h4 #{ko_text :title}
        %label.checkbox
          %input{type:"checkbox", data: {bind: "checked: visible"}}
          Visible

      %div{data: {bind: "if: visible()"}}
        /ko foreach: solutions
        .link{ko(click: '$root.selectSolution')}
          #{ko_text :studentInfo}
          %span.pull-right{data:{bind: "html: showSolutionStatus()"}}
          %br

        //ko



    //ko

  /ko with: selectedSolution
  .span8.well{data: {bind: "visible: code"}}

    %h3
      Solución
    %h4
      %pre
        %code.haskell{ko(text: :code)}

    //ko

  //ko

:javascript
  initTeacher(#{@problem_group.id}, #{@problem_group.teacher_status.to_json});